# Generated by Django 6.1.1 on 2026-09-18 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Alt text or title for slide', max_length=200)),
                ('image', models.ImageField(upload_to='carousel/')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of display (0, 1, 2...)')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(default='Plant Protection Association of India', max_length=255)),
                ('registration_info', models.CharField(default='(Regn. No. S399 of 1949-50 under the Societies Registration Act XXI of 1860)', max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logo/')),
                ('hero_badge', models.CharField(default='Since 1972', max_length=50)),
                ('hero_title', models.CharField(default='Indian Journal of Plant Protection', max_length=255)),
                ('hero_description', models.TextField(default='The Indian Journal of Plant Protection (IJPP) is a peer-reviewed quarterly journal published by the Plant Protection Association of India (PPAI), Hyderabad. It publishes original research, reviews, and short communications in agricultural entomology, plant pathology, nematology, weed science, and integrated pest management (IPM).')),
                ('members_count', models.CharField(default='1,900+', max_length=50)),
                ('society_years', models.CharField(default='54', max_length=50)),
                ('published_volumes', models.CharField(default='54', max_length=50)),
            ],
            options={
                'verbose_name': 'Site Setting',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
