# Generated by Django 6.1.1 on 2026-09-19 11:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConferenceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('event_title', models.TextField()),
            ],
            options={
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='EditorialBoardMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(choices=[('chief_editor', 'Editor-in-Chief'), ('assoc_editor', 'Associate Editor'), ('member', 'Editorial Member'), ('intl_member', 'Editorial Member (International)')], max_length=20)),
                ('institution', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ExecutiveMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=150)),
                ('affiliation', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Executive Council Member',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='JournalArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.IntegerField(default=54)),
                ('issue', models.IntegerField(default=1)),
                ('year', models.IntegerField(default=2026)),
                ('title', models.CharField(max_length=300)),
                ('authors', models.CharField(max_length=300)),
                ('abstract', models.TextField(blank=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='journals/pdf/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
            ],
            options={
                'ordering': ['-volume', '-issue', 'id'],
            },
        ),
        migrations.CreateModel(
            name='JournalVolume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume_number', models.IntegerField()),
                ('year', models.IntegerField()),
                ('issues_available', models.CharField(default='No. 1, No. 2', max_length=255)),
                ('epubs_url', models.URLField(default='https://epubs.icar.org.in/index.php/IJPP')),
            ],
            options={
                'ordering': ['-volume_number'],
            },
        ),
        migrations.CreateModel(
            name='PastBearer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(choices=[('president', 'Past President'), ('secretary', 'Past General Secretary'), ('treasurer', 'Past Treasurer'), ('editor', 'Past Chief Editor')], max_length=20)),
                ('tenure', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['role', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PublicationBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='SocietyAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('conferred_for', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='carouselslide',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='carouselslide',
            name='title',
            field=models.CharField(blank=True, help_text='Title or alt text', max_length=200),
        ),
    ]
