# Generated by Django 6.1.1 on 2026-09-19 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_conferenceevent_editorialboardmember_executivemember_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='executivemember',
            name='bio',
            field=models.TextField(blank=True, help_text='Short bio / description'),
        ),
        migrations.AddField(
            model_name='executivemember',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=10),
        ),
        migrations.AddField(
            model_name='executivemember',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload member photo. Defaults to gender avatar if blank.', null=True, upload_to='council/'),
        ),
        migrations.AddField(
            model_name='pastbearer',
            name='affiliation',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='pastbearer',
            name='bio',
            field=models.TextField(blank=True, help_text='Short bio / contribution details'),
        ),
        migrations.AddField(
            model_name='pastbearer',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=10),
        ),
        migrations.AddField(
            model_name='pastbearer',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload past bearer photo. Defaults to gender avatar if blank.', null=True, upload_to='legends/'),
        ),
    ]
